### ISSUE TITLE
scenes folder empty?

### ISSUE THREAD

**Issue by jespertheend** [Curdflappers/UltimateTicTacToe#1]
It seems like the scenes folder is empty, is this intended?
It only has some meta files but doesn't contain the actual unity scenes.

**Comment by jespertheend** [comment]
Never mind, I was in the wrong branch. This one does seem to be a lot older though.

**Comment by mark-wiemer** [comment]
I've stopped uploading the binary files for the scenes and builds, as that isn't recommended for commits (if I have to undo a commit, reading that binary is basically impossible). A working version of the game for Windows and Android is included in every release, and you can see how I've set up my scenes there.

**Comment by jespertheend** [comment]
Ah alright, I'll check it out. Thanks!
